spring.application.name=front-ui
server.port=8089

spring.config.import=optional:consul:${CONSUL_HOST:localhost}:8500
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=PROPERTIES
spring.cloud.consul.config.data-key=data
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.defaultContext=application
spring.cloud.consul.config.watch.enabled=false
spring.cloud.consul.config.watch.delay=100000

spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${spring.application.name}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_FRONT_UI_SECRET:5eOiAHGLM8KvD2xxMRcCeIogKaFtnN3P}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/realms/${KEYCLOAK_REALM:my-bank-app-realm}