spring.kafka.bootstrap-servers=${KAFKA_URI:kafka:9092}
spring.kafka.topics.enabled=true
#spring.kafka.topics.topic=${KAFKA_TOPIC:notifications-to-notifications}
#spring.kafka.topics.partitions=${KAFKA_PARTITIONS:3}
#spring.kafka.topics.replicas=${KAFKA_REPLICAS:1}
spring.kafka.admin.client-id=my-bank-app
spring.kafka.admin.fail-fast=true
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:my-bank-app-consumer}
spring.kafka.consumer.properties.spring.json.trusted.packages="io.github.wolfandw.chassis.dto"