spring.kafka.bootstrap-servers=${KAFKA_URI:kafka:9092}
spring.kafka.topics.enabled=true
spring.kafka.topics.partitions=${KAFKA_PARTITIONS:3}
spring.kafka.topics.replicas=${KAFKA_REPLICAS:1}
#spring.kafka.consumer.group-id=my-bank-app-consumer-group
#spring.kafka.consumer.properties.spring.json.trusted.packages=io.github.wolfandw.chassis.model
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.UUIDDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
#spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.admin.client-id=my-bank-app
spring.kafka.admin.fail-fast=true