spring.kafka.bootstrap-servers=${KAFKA_URI:localhost:9094}
spring.kafka.topics.enabled=true
spring.kafka.topics.partitions=${KAFKA_PARTITIONS:3}
spring.kafka.topics.replicas=${KAFKA_REPLICAS:1}
spring.kafka.admin.client-id=my-bank-app
spring.kafka.admin.fail-fast=true

accounts.kafka.topic=${ACCOUNTS_KAFKA_TOPIC:accounts-to-notifications}
cash.kafka.topic=${CASH_KAFKA_TOPIC:cash-to-notifications}
transfer.kafka.topic=${TRANSFER_KAFKA_TOPIC:transfer-to-notifications}