gateway.host=${GATEWAY_HOST:localhost}
gateway.port=${GATEWAY_PORT:8081}

accounts.host=${ACCOUNT_HOST:localhost}
accounts.port=${ACCOUNT_PORT:8083}

notifications.host=${NOTIFICATIONS_HOST:localhost}
notifications.port=${NOTIFICATIONS_PORT:8086}

spring.kafka.bootstrap-servers=${KAFKA_URI:localhost:9094}
spring.kafka.topics.enabled=true
spring.kafka.topics.partitions=${KAFKA_PARTITIONS:3}
spring.kafka.topics.replicas=${KAFKA_REPLICAS:1}
spring.kafka.admin.client-id=my-bank-app
spring.kafka.admin.fail-fast=true

accounts.kafka.topic=${ACCOUNTS_KAFKA_TOPIC:accounts-to-notifications}
cash.kafka.topic=${CASH_KAFKA_TOPIC:cash-to-notifications}
transfer.kafka.topic=${TRANSFER_KAFKA_TOPIC:transfer-to-notifications}

management.endpoints.web.exposure.include=health,info,metrics,tracing,zipkin
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0

spring.task.scheduling.observability.enabled=false