apiVersion: v2
name: my-bank-app-chart
description: Зонтичный Helm-чарт для my-bank-app
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: keycloak-chart
    version: "26.3.1"
    repository: "file://charts/keycloak-chart"
    alias: keycloak

  - name: postgres-chart
    version: 0.1.0
    repository: "file://charts/postgres-chart"
    alias: accountsdata

  - name: postgres-chart
    version: 0.1.0
    repository: "file://charts/postgres-chart"
    alias: cashdata

  - name: postgres-chart
    version: 0.1.0
    repository: "file://charts/postgres-chart"
    alias: notificationdata

  - name: postgres-chart
    version: 0.1.0
    repository: "file://charts/postgres-chart"
    alias: transferdata

  - name: accounts-chart
    repository: "file://charts/accounts-chart"

  - name: cash-chart
    repository: "file://charts/cash-chart"

  - name: gateway-chart
    repository: "file://charts/gateway-chart"

  - name: frontui-chart
    repository: "file://charts/frontui-chart"

  - name: notifications-chart
    repository: "file://charts/notifications-chart"

  - name: transfer-chart
    repository: "file://charts/transfer-chart"
