global:
  namespace: prod

accounts-chart:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

cash-chart:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

notifications-chart:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

transfer-chart:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

frontui-chart:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

gateway:
  replicaCount: 3
  resources:
    limits: { memory: "2Gi", cpu: "2000m" }
    requests: { memory: "1Gi", cpu: "500m" }

account-db:
  persistence: { size: 3Gi, storageClass: "premium-rwo" }

keycloak:
  postgresql:
    persistence: { size: 3Gi, storageClass: "premium-rwo" }