global:
  namespace: dev

accounts:
  replicaCount: 1
  resources:
    limits: { memory: "512Mi", cpu: "500m" }
    requests: { memory: "256Mi", cpu: "100m" }

cash:
  replicaCount: 1
  resources:
    limits: { memory: "512Mi", cpu: "500m" }
    requests: { memory: "256Mi", cpu: "100m" }

notifications:
  replicaCount: 1
  resources:
    limits: { memory: "512Mi", cpu: "500m" }
    requests: { memory: "256Mi", cpu: "100m" }

transfer:
  replicaCount: 1
  resources:
    limits: { memory: "512Mi", cpu: "500m" }
    requests: { memory: "256Mi", cpu: "100m" }

frontui:
  replicaCount: 1
  resources:
    limits: { memory: "512Mi", cpu: "500m" }
    requests: { memory: "256Mi", cpu: "100m" }

gateway:
  replicaCount: 1
  resources:
    limits: { memory: "768Mi", cpu: "500m" }
    requests: { memory: "512Mi", cpu: "200m" }

accountsdata: { persistence: { enabled: false } }
cashdata: { persistence: { enabled: false } }
notificationsdata: { persistence: { enabled: false } }
transferdata: { persistence: { enabled: false } }
keycloak: { postgresql: { persistence: { enabled: false } } }