accountdata:
  postgres:
    db: accounts_db
    user: postgres
    password: postgres
  persistence:
    size: 1Gi
    enabled: true

cashdata:
  postgres:
    db: cash_db
    user: postgres
    password: postgres
  persistence:
    size: 1Gi
    enabled: true

notificationsdata:
  postgres:
    db: notifications_db
    user: postgres
    password: postgres
  persistence:
    size: 1Gi
    enabled: true

transferdata:
  postgres:
    db: transfer_db
    user: postgres
    password: postgres
  persistence:
    size: 1Gi
    enabled: true

global:
  db:
    user: "postgres"
    port: "5432"
  keycloak:
    url: "http://keycloak"
    port: "8080"
    realm: "my-bank-app-realm"
  gateway:
    host: "http://gateway:8080"

keycloak:
  service:
    type: ClusterIP
    ports:
      http: 80
    targetPort: 8080

  postgresql:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: "17.6.0-debian-12-r4"

  image:
    registry: docker.io
    repository: bitnamilegacy/keycloak
    tag: "26.3.3"

  fullnameOverride: keycloak

  auth:
    adminUser: admin
    adminPassword: admin

  persistence:
    deployPostgresql: true

  extraEnvVars:
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: "admin"
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      value: "admin"
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_HTTP_ENABLED
      value: "true"
    - name: KC_HOSTNAME
      value: "keycloak"
    - name: KC_IMPORT_STRATEGY
      value: "OVERWRITE_EXISTING"
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
    - name: KC_HTTP_MANAGEMENT_PORT
      value: "9000"

  extraVolumes:
    - name: realm-import-raw
      configMap:
        name: keycloak-import
    - name: realm-import-writable
      emptyDir: { }

  extraVolumeMounts:
    - name: realm-import-writable
      mountPath: /opt/bitnami/keycloak/data/import

  initContainers:
    - name: prepare-realm
      image: busybox:1.36
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          set -e
          cp -v /cm/*.json /opt/bitnami/keycloak/data/import/
      volumeMounts:
        - name: realm-import-raw
          mountPath: /cm
        - name: realm-import-writable
          mountPath: /opt/bitnami/keycloak/data/import