services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    command: start-dev
      --import-realm
      --http-port=8080
      --http-enabled=true
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    ports:
      - "8080:8080"
      - "9000:9000"
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/ready' ]
      interval: 5s
      timeout: 5s
      retries: 20

  kafka:
    image: bitnamilegacy/kafka:3.5.1-debian-11-r61
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_CLUSTERS_NAME}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true

  zipkin:
    image: openzipkin/zipkin:3.5
    container_name: zipkin
    depends_on:
      - kafka
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9411/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  accountsdata:
    image: postgres:17-alpine
    container_name: accountsdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ACCOUNTS_DB_NAME}
      POSTGRES_USER: ${ACCOUNTS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNTS_DB_PASSWORD}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ACCOUNTS_DB_USERNAME} -d ${ACCOUNTS_DB_NAME}" ]
      interval: 5s

  cashdata:
    image: postgres:17-alpine
    container_name: cashdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CASH_DB_NAME}
      POSTGRES_USER: ${CASH_DB_USERNAME}
      POSTGRES_PASSWORD: ${CASH_DB_PASSWORD}
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CASH_DB_USERNAME} -d ${CASH_DB_NAME}" ]
      interval: 5s

  transferdata:
    image: postgres:17-alpine
    container_name: transferdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TRANSFER_DB_NAME}
      POSTGRES_USER: ${TRANSFER_DB_USERNAME}
      POSTGRES_PASSWORD: ${TRANSFER_DB_PASSWORD}
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TRANSFER_DB_USERNAME} -d ${TRANSFER_DB_NAME}" ]
      interval: 5s

  notificationsdata:
    image: postgres:17-alpine
    container_name: notificationsdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NOTIFICATIONS_DB_NAME}
      POSTGRES_USER: ${NOTIFICATIONS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOTIFICATIONS_DB_PASSWORD}
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NOTIFICATIONS_DB_USERNAME} -d ${NOTIFICATIONS_DB_NAME}" ]
      interval: 5s

volumes:
  kafka_data:
    driver: local