services:

  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    command: [ "agent","-dev","-ui","-client","0.0.0.0", "-log-level","ERROR" ]
    ports:
      - "8500:8500"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 5s
      timeout: 3s
      retries: 5

#  keycloak:
#    image: quay.io/keycloak/keycloak:26.3.1
#    container_name: keycloak
#    command: start-dev --import-realm --http-port=8082
#    environment:
#      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
#      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
#    volumes:
#      - .:/opt/keycloak/data/import
#    ports:
#      - "8082:8082"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://keycloak:8082/health/ready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5