services:

  consul:
    container_name: consul
    build:
      context: .
      dockerfile: ./consul/Dockerfile
    ports:
      - "8500:8500"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://consul:8500/v1/status/leader" ]
      interval: 5s
      timeout: 3s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.1
    container_name: keycloak
    command: start-dev
      --import-realm
      --http-port=8080
      --http-enabled=true
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak/data:/opt/keycloak/data/import
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      consul:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/ready' ]
      interval: 5s
      timeout: 5s
      retries: 20

  accountsdata:
    image: postgres:17-alpine
    container_name: accountsdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${ACCOUNTS_DB_NAME}
      POSTGRES_USER: ${ACCOUNTS_DB_USERNAME}
      POSTGRES_PASSWORD: ${ACCOUNTS_DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${ACCOUNTS_DB_USERNAME} -d ${ACCOUNTS_DB_NAME}" ]
      interval: 5s

  cashdata:
    image: postgres:17-alpine
    container_name: cashdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${CASH_DB_NAME}
      POSTGRES_USER: ${CASH_DB_USERNAME}
      POSTGRES_PASSWORD: ${CASH_DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CASH_DB_USERNAME} -d ${CASH_DB_NAME}" ]
      interval: 5s

  transferdata:
    image: postgres:17-alpine
    container_name: transferdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TRANSFER_DB_NAME}
      POSTGRES_USER: ${TRANSFER_DB_USERNAME}
      POSTGRES_PASSWORD: ${TRANSFER_DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TRANSFER_DB_USERNAME} -d ${TRANSFER_DB_NAME}" ]
      interval: 5s

  notificationsdata:
    image: postgres:17-alpine
    container_name: notificationsdata
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${NOTIFICATIONS_DB_NAME}
      POSTGRES_USER: ${NOTIFICATIONS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NOTIFICATIONS_DB_PASSWORD}
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${NOTIFICATIONS_DB_USERNAME} -d ${NOTIFICATIONS_DB_NAME}" ]
      interval: 5s

  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: ./notifications/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - NOTIFICATIONS_DB_HOST=localhost
      - NOTIFICATIONS_DB_PORT=5436
      - NOTIFICATIONS_DB_NAME=${NOTIFICATIONS_DB_NAME}
      - NOTIFICATIONS_DB_USERNAME=${NOTIFICATIONS_DB_USERNAME}
      - NOTIFICATIONS_DB_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_NOTIFICATIONS_SECRET=${KEYCLOAK_NOTIFICATIONS_SECRET}
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      notificationsdata:
        condition: service_healthy
    ports:
      - "8086:8086"

  accounts:
    container_name: accounts
    build:
      context: .
      dockerfile: ./accounts/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - ACCOUNTS_DB_HOST=localhost
      - ACCOUNTS_DB_PORT=5433
      - ACCOUNTS_DB_NAME=${ACCOUNTS_DB_NAME}
      - ACCOUNTS_DB_USERNAME=${ACCOUNTS_DB_USERNAME}
      - ACCOUNTS_DB_PASSWORD=${ACCOUNTS_DB_PASSWORD}
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_ACCOUNTS_SECRET=${KEYCLOAK_ACCOUNTS_SECRET}
      - NOTIFICATIONS_HOST=localhost
      - NOTIFICATIONS_PORT=8086
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      accountsdata:
        condition: service_healthy
      notifications:
        condition: service_started
    ports:
      - "8083:8083"
    restart: unless-stopped

  cash:
    container_name: cash
    build:
      context: .
      dockerfile: ./cash/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - CASH_DB_HOST=localhost
      - CASH_DB_PORT=5434
      - CASH_DB_NAME=${CASH_DB_NAME}
      - CASH_DB_USERNAME=${CASH_DB_USERNAME}
      - CASH_DB_PASSWORD=${CASH_DB_PASSWORD}
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CASH_SECRET=${KEYCLOAK_CASH_SECRET}
      - NOTIFICATIONS_HOST=localhost
      - NOTIFICATIONS_PORT=8086
      - ACCOUNT_HOST=accounts
      - ACCOUNT_PORT=8083
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      cashdata:
        condition: service_healthy
      notifications:
        condition: service_started
      accounts:
        condition: service_started
    ports:
      - "8084:8084"

  transfer:
    container_name: transfer
    build:
      context: .
      dockerfile: ./transfer/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - TRANSFER_DB_HOST=localhost
      - TRANSFER_DB_PORT=5435
      - TRANSFER_DB_NAME=${TRANSFER_DB_NAME}
      - TRANSFER_DB_USERNAME=${NOTIFICATIONS_DB_USERNAME}
      - TRANSFER_DB_PASSWORD=${NOTIFICATIONS_DB_PASSWORD}
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_TRANSFER_SECRET=${KEYCLOAK_TRANSFER_SECRET}
      - NOTIFICATIONS_HOST=localhost
      - NOTIFICATIONS_PORT=8086
      - ACCOUNT_HOST=accounts
      - ACCOUNT_PORT=8083
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      transferdata:
        condition: service_healthy
      notifications:
        condition: service_started
      accounts:
        condition: service_started
    ports:
      - "8085:8085"

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_GATEWAY_SECRET=${KEYCLOAK_GATEWAY_SECRET}
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      notifications:
        condition: service_started
      accounts:
        condition: service_started
      cash:
        condition: service_started
      transfer:
        condition: service_started
    ports:
      - "8081:8081"

  frontui:
    container_name: frontui
    build:
      context: .
      dockerfile: ./frontui/Dockerfile
    network_mode: host
    environment:
      - CONSUL_HOST=localhost
      - CONSUL_PORT=8500
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=8081
      - KEYCLOAK_HOST=localhost
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_FRONT_UI_SECRET=${KEYCLOAK_FRONT_UI_SECRET}
    depends_on:
      consul:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      notifications:
        condition: service_started
      accounts:
        condition: service_started
      cash:
        condition: service_started
      transfer:
        condition: service_started
      gateway:
        condition: service_started
    ports:
      - "8089:8089"