apiVersion: 1

groups:
  - orgId: 1
    name: 'my-bank-alerts'
    folder: 'My Bank Metrics'
    interval: 10s
    rules:
      - uid: 'alert_cash_transfer_fail'
        title: 'CRITICAL: Рост недостаточности средств при переводе денег'
        condition: 'C'
        for: '1m'
        annotations:
          summary: 'Рост недостаточности средств при переводе денег!'
          description: 'Текущая скорость ошибок: {{ $values.C }} оп/сек. Проверьте балансы пользователей.'
        labels:
          severity: 'critical'
          tier: 'business'
        data:
          - refId: 'A'
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: 'Prometheus'
            model:
              expr: 'increase(transfer_cash_total{status="failure"}[1m])'
              refId: 'A'
          - refId: 'B'
            datasourceUid: '-100'
            model: { expression: 'A', reducer: 'max', type: 'reduce', refId: 'B' }
          - refId: 'C'
            datasourceUid: '-100'
            model:
              expression: 'B'
              type: 'threshold'
              refId: 'C'
              conditions:
                - evaluator:
                    # Порог более 5 ошибок суммарно за минуту
                    params: [ 5.0 ]
                    type: 'gt'
                  query:
                    params: [ 'B' ]
                  reducer:
                    params: [ ]
                    type: 'avg'

      - uid: 'alert_notifications_fail'
        title: 'WARNING: Пользователи не получают уведомления'
        condition: 'C'
        for: '2m'
        annotations:
          summary: 'Пользователи не получают уведомления!'
          description: 'Ошибки отправки нотификаций выросли до {{ $values.C }} оп/сек.'
        labels:
          severity: 'warning'
          tier: 'business'
        data:
          - refId: 'A'
            relativeTimeRange: { from: 300, to: 0 }
            datasourceUid: 'Prometheus'
            model:
              expr: 'rate(send_unsent_notification_total{status="failure"}[1m])'
              refId: 'A'
          - refId: 'B'
            datasourceUid: '-100'
            model: { expression: 'A', reducer: 'max', type: 'reduce', refId: 'B' }
          - refId: 'C'
            datasourceUid: '-100'
            model:
              expression: 'B'
              type: 'threshold'
              refId: 'C'
              conditions:
                - evaluator:
                    params: [1.0]
                    type: 'gt'
                  query:
                    params: ['B']
                  reducer:
                    params: []
                    type: 'avg'
