spring.application.name=gateway
server.port=8081

spring.cloud.gateway.server.webflux.routes[0].id=accounts-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://accounts:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/account
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/account, /api/account

spring.cloud.gateway.server.webflux.routes[1].id=cash-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://cash:8084
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/cash

spring.cloud.gateway.server.webflux.routes[2].id=transfer-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://transfer:8085
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transfer

spring.config.import=optional:consul:localhost:8500
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=PROPERTIES
spring.cloud.consul.config.data-key=data
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.defaultContext=application
spring.cloud.consul.config.watch.enabled=true
spring.cloud.consul.config.watch.delay=1000
