spring.application.name=gateway
server.port=8081

spring.cloud.gateway.server.webflux.routes[0].id=accounts-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/account
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/some-service/?(?<segment>.*), /$\{segment}

spring.cloud.gateway.server.webflux.routes[1].id=cash-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/cash/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/some-service/?(?<segment>.*), /$\{segment}

spring.cloud.gateway.server.webflux.routes[2].id=transfer-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transfer/**
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/some-service/?(?<segment>.*), /$\{segment}
