spring.application.name=gateway
server.port=${GATEWAY_PORT:8081}

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=accounts-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://${ACCOUNT_HOST:localhost}:${ACCOUNT_PORT:8083}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/account
spring.cloud.gateway.server.webflux.routes[0].filters[0]=TokenRelay=

spring.cloud.gateway.server.webflux.routes[1].id=cash-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://${CASH_HOST:localhost}:${CASH_PORT:8084}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/cash
spring.cloud.gateway.server.webflux.routes[1].filters[0]=TokenRelay=

spring.cloud.gateway.server.webflux.routes[2].id=transfer-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://${TRANSFER_HOST:localhost}:${TRANSFER_PORT:8085}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/transfer
spring.cloud.gateway.server.webflux.routes[2].filters[0]=TokenRelay=

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-bank-app-realm}
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${spring.application.name}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_GATEWAY_SECRET:27gcWzuNZoOpmR3SygtMFjXr3apPjhVW}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-bank-app-realm}

management.endpoints.web.exposure.include=health,info,refresh,metrics,tracing,zipkin,prometheus
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histograms.http.server.requests=true