spring.application.name=cash
server.port=8084

spring.config.import=optional:consul:${CONSUL_HOST:localhost}:8500
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=PROPERTIES
spring.cloud.consul.config.data-key=data
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.defaultContext=application
spring.cloud.consul.config.watch.enabled=true
spring.cloud.consul.config.watch.delay=1000