spring.application.name=cash
server.port=8084

spring.r2dbc.url=r2dbc:postgresql://${CASH_DB_HOST:localhost}:${CASH_DB_PORT:5434}/${CASH_DB_NAME:cash_db}?sslMode=disable
spring.r2dbc.username=${CASH_DB_USERNAME:postgres}
spring.r2dbc.password=${CASH_DB_PASSWORD:postgres}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.liquibase.url= jdbc:postgresql://${CASH_DB_HOST:localhost}:${CASH_DB_PORT:5434}/${CASH_DB_NAME:cash_db}?sslMode=disable
spring.liquibase.user=${CASH_DB_USERNAME:postgres}
spring.liquibase.password=${CASH_DB_PASSWORD:postgres}
spring.liquibase.enabled=true
spring.liquibase.contexts=prod
spring.liquibase.change-log=classpath:/db/changelog/cash/db.changelog-master.xml

spring.config.import=optional:consul:${CONSUL_HOST:localhost}:8500
spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${random.value}
spring.cloud.consul.config.enabled=true
spring.cloud.consul.config.format=PROPERTIES
spring.cloud.consul.config.data-key=data
spring.cloud.consul.config.prefix=config
spring.cloud.consul.config.defaultContext=application
spring.cloud.consul.config.watch.enabled=true
spring.cloud.consul.config.watch.delay=1000