spring.application.name=accounts
server.port=${ACCOUNT_PORT:8083}

spring.r2dbc.url=r2dbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT:5433}/${ACCOUNTS_DB_NAME:accounts_db}
spring.r2dbc.username=${ACCOUNTS_DB_USERNAME:postgres}
spring.r2dbc.password=${ACCOUNTS_DB_PASSWORD:postgres}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.datasource.url=jdbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT:5433}/${ACCOUNTS_DB_NAME:accounts_db}
spring.datasource.username=${ACCOUNTS_DB_USERNAME:postgres}
spring.datasource.password=${ACCOUNTS_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.url= jdbc:postgresql://${ACCOUNTS_DB_HOST:localhost}:${ACCOUNTS_DB_PORT:5433}/${ACCOUNTS_DB_NAME:accounts_db}
spring.liquibase.user=${ACCOUNTS_DB_USERNAME:postgres}
spring.liquibase.password=${ACCOUNTS_DB_PASSWORD:postgres}
spring.liquibase.enabled=true
spring.liquibase.contexts=prod
spring.liquibase.change-log=classpath:/db/changelog/accounts/db.changelog-master.xml

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/my-bank-app-realm/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-bank-app-realm}
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-id=${spring.application.name}
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_ACCOUNTS_SECRET:OJ59Qho7qss9aAAFHShOOWiiIVo3wuE7}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/my-bank-app-realm}

spring.kafka.topics.topic=${ACCOUNTS_KAFKA_TOPIC:accounts-to-notifications}

management.metrics.tags.application=${spring.application.name}
management.endpoints.web.exposure.include=health,info,refresh,metrics,tracing,zipkin,prometheus
management.zipkin.tracing.endpoint=${ZIPKIN_URI:http://localhost:9411/api/v2/spans}
management.tracing.sampling.probability=1.0
management.metrics.distribution.percentiles-histograms.http.server.requests=true