{
 "title": "My Bank Metrics",
 "tags": [ "business" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Снятие наличных (Change Cash Get Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(change_cash_get_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Переводы денег (Transfer Cash Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    { "expr": "rate(transfer_cash_total[1m])", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Отправка сообщений в сервис нотификаций (Send Unsent Outbox)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(send_unsent_outbox_total[1m])",
     "legendFormat": "{{status}} ({{application}})"
    }
   ]
  },
  {
   "title": "Отправка нотификаций получателям (Send Unsent Notification)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(send_unsent_notification_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}