apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "dev" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: my-bank-app-config
          env:
            - name: NOTIFICATIONS_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: NOTIFICATIONS_DB_USERNAME
            - name: NOTIFICATIONS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: NOTIFICATIONS_DB_PASSWORD
            - name: KEYCLOAK_NOTIFICATIONS_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: KEYCLOAK_NOTIFICATIONS_SECRET