apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Chart.Name } }
  namespace: { { .Release.Namespace | default "dev" } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: { { .Chart.Name } }
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-bank-app-config
          env:
            - name: CASH_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: CASH_DB_USERNAME
            - name: CASH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: CASH_DB_PASSWORD
            - name: CASH_DB_HOST
              value: "my-bank-app-chart-cashdata"
            - name: CASH_DB_PORT
              value: "5433"
            - name: CASH_DB_NAME
              value: "cash_db"
            - name: KEYCLOAK_CASH_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-bank-app-secrets
                  key: KEYCLOAK_CASH_SECRET
            - name: KEYCLOAK_HOST
              value: "keycloak"
            - name: KEYCLOAK_PORT
              value: "8080"
            - name: KEYCLOAK_REALM
              value: "my-bank-app-realm"