input {
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  date {
    match => ["@timestamp", "ISO8601"]
  }
  if [mdc][traceId] {
    mutate {
      add_field => { "traceId" => "%{[mdc][traceId]}" }
      add_field => { "spanId" => "%{[mdc][spanId]}" }
    }
  }
  if [logger_name] == "io.github.wolfandw.chassis.filter.LoggingWebFilter" {
    grok {
      match => {
        "message" => "Method: %{WORD:http_method}, URI: %{NOTSPACE:http_uri}, status: %{NUMBER:http_status_code} %{WORD:http_status_text}, time: %{NUMBER:http_response_time_ms}ms"
        }
      add_tag => [ "http_request" ]
    }

    mutate {
      convert => {
        "http_status_code" => "integer"
        "http_response_time_ms" => "integer"
      }
    }
  }
  if [logger_name] == "io.github.wolfandw.notifications.service.impl.NotificationsServiceImpl" {
      grok {
            match => {
              "message" => [
                "Notifications. Уведомление отправлено: 'Accounts. Недостаточно средств на счете для перевода получателю: %{DATA:recipient}, пользователь: %{DATA:login}'",
                "Notifications. Уведомление отправлено: 'Accounts. Недостаточно средств на счете для списания, пользователь: %{DATA:login}'",
                "Notifications. Уведомление НЕ отправлено: '%{DATA:_ignored}, пользователь: %{DATA:login}'"
              ]
            }
          }

          if [recipient] {
            mutate {
              add_tag => [ "business_transfer_cash_fail" ]
            }
          } else if "НЕ отправлено" in [message] {
            mutate {
              add_tag => [ "business_send_unsent_notification_fail" ]
              remove_field => [ "_ignored" ]
            }
          } else if "для списания" in [message] {
            mutate {
              add_tag => [ "business_change_cash_fail" ]
            }
          }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "my-bank-app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}

