spring.application.name=notifications
server.port=${NOTIFICATIONS_PORT:8086}

spring.kafka.topics.topic=${NOTIFICATIONS_TO_NOTIFICATIONS_KAFKA_TOPIC:notifications-to-notifications}

spring.r2dbc.url=r2dbc:postgresql://${NOTIFICATIONS_DB_HOST:localhost}:${NOTIFICATIONS_DB_PORT:5436}/${NOTIFICATIONS_DB_NAME:notifications_db}
spring.r2dbc.username=${NOTIFICATIONS_DB_USERNAME:postgres}
spring.r2dbc.password=${NOTIFICATIONS_DB_PASSWORD:postgres}
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.datasource.url=jdbc:postgresql://${NOTIFICATIONS_DB_HOST:localhost}:${NOTIFICATIONS_DB_PORT:5436}/${NOTIFICATIONS_DB_NAME:notifications_db}
spring.datasource.username=${NOTIFICATIONS_DB_USERNAME:postgres}
spring.datasource.password=${NOTIFICATIONS_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.url= jdbc:postgresql://${NOTIFICATIONS_DB_HOST:localhost}:${NOTIFICATIONS_DB_PORT:5436}/${NOTIFICATIONS_DB_NAME:notifications_db}
spring.liquibase.user=${NOTIFICATIONS_DB_USERNAME:postgres}
spring.liquibase.password=${NOTIFICATIONS_DB_PASSWORD:postgres}
spring.liquibase.enabled=true
spring.liquibase.contexts=prod
spring.liquibase.change-log=classpath:/db/changelog/notifications/db.changelog-master.xml