apiVersion: v1
kind: Secret
metadata:
  name: my-bank-app-secrets
type: Opaque
stringData:
  ACCOUNTS_DB_USERNAME: {{ .Values.stringData.accountDbUsername }}
  ACCOUNTS_DB_PASSWORD: {{ .Values.stringData.accountsDbPassword }}

  CASH_DB_USERNAME: {{ .Values.stringData.cashDbUsername }}
  CASH_DB_PASSWORD: {{ .Values.stringData.cashDbPassword }}

  TRANSFER_DB_USERNAME: {{ .Values.stringData.transferDbUsername }}
  TRANSFER_DB_PASSWORD: {{ .Values.stringData.transferDbPassword }}

  NOTIFICATIONS_DB_USERNAME: {{ .Values.stringData.notificationsDbUsername }}
  NOTIFICATIONS_DB_PASSWORD: {{ .Values.stringData.notificationsDbPassword }}

  KEYCLOAK_ACCOUNTS_SECRET: {{ .Values.stringData.keycloakAccountsSecret }}
  KEYCLOAK_CASH_SECRET: {{ .Values.stringData.keycloakCashSecret }}
  KEYCLOAK_FRONT_UI_SECRET: {{ .Values.stringData.keycloakFrontUiSecret }}
  KEYCLOAK_GATEWAY_SECRET: {{ .Values.stringData.keycloakGatewaySecret }}
  KEYCLOAK_NOTIFICATIONS_SECRET: {{ .Values.stringData.keycloakNotificationsSecret }}
  KEYCLOAK_TRANSFER_SECRET: {{ .Values.stringData.keycloakTransferSecret }}