apiVersion: v1
kind: Secret
metadata:
  name: my-bank-app-secrets
type: Opaque
stringData:
  ACCOUNTS_DB_USERNAME: "postgres"
  ACCOUNTS_DB_PASSWORD: "postgres"

  CASH_DB_USERNAME: "postgres"
  CASH_DB_PASSWORD: "postgres"

  TRANSFER_DB_USERNAME: "postgres"
  TRANSFER_DB_PASSWORD: "postgres"

  NOTIFICATIONS_DB_USERNAME: "postgres"
  NOTIFICATIONS_DB_PASSWORD: "postgres"

  KEYCLOAK_ACCOUNTS_SECRET: "OJ59Qho7qss9aAAFHShOOWiiIVo3wuE7"
  KEYCLOAK_CASH_SECRET: "Isq0cW1jwx9GIQypRuCX6CEozSPG3xT8"
  KEYCLOAK_FRONT_UI_SECRET: "5eOiAHGLM8KvD2xxMRcCeIogKaFtnN3P"
  KEYCLOAK_GATEWAY_SECRET: "27gcWzuNZoOpmR3SygtMFjXr3apPjhVW"
  KEYCLOAK_NOTIFICATIONS_SECRET: "dYULgKXgzByDWxcH8SQ5PIQ9CGWLgMZ0"
  KEYCLOAK_TRANSFER_SECRET: "0HkSVUblZIWjdaswozGgOSwD9LpPYFDb"

  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"